name: Publish distributions to PyPI

on:
  release:
    types:
      - released

jobs:
  shared-build-and-publish:
    uses: zigpy/workflows/.github/workflows/publish-to-pypi.yml@main
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
